#ifndef __CDR_H__
#define __CDR_H__

#include <pthread.h>
#include <semaphore.h>

#include <minigui/window.h>

#include "misc.h"

#define TIME_INFINITE 0xFFFFFF
#ifdef HERO_OLEDUI
#define WIN_CNT 7
#else
#define WIN_CNT 9
#endif

#define LOW_POWER  10

enum {
	WATERMARK_TWM = 0x1,	//time water mark
	WATERMARK_LWM = 0x2,	//plate water mark
};

/* Window ID*/
enum {
	WINDOWID_RECORDPREVIEW = 0,
	WINDOWID_MENU,
	WINDOWID_PLAYBACKPREVIEW,
	WINDOWID_PLAYBACK,
	WINDOWID_STATUSBAR,
	WINDOWID_MAIN,
	WINDOWID_MAINPREVIEW,
	WINDOWID_OTHERPREVIEW,
	WINDOWID_MODEPREVIEW,
#ifdef HERO_OLEDUI	
	WINDOWID_OLEDUI,
#endif
	WINDOWID_INVALID
};

#define CDR_FILE_LENGHT			100
#define FORMATTF_TIMER 			10001

enum {
	MSG_RM_MSG_BASE = MSG_USER,
	MSG_RM_LANG_CHANGED,
	MSG_RM_VIDEO_BITRATE,
	MSG_RM_VIDEO_RESOLUTION,
	MSG_RM_PIC_RESOLUTION,
	MSG_RM_PIC_QUALITY,
	MSG_RM_PIC_TIMETAKEPHOTOS,
	MSG_RM_PIC_AUTOMATICTAKEPHOTOS,
	MSG_RM_PIC_MOTIONTAKEPHOTOS,
	MSG_RM_VIDEO_TIME_LENGTH,
	MSG_RM_WHITEBALANCE,
	MSG_RM_CONTRAST,
	MSG_RM_EXPOSURE,
	MSG_RM_SCREENSWITCH,
	MSG_RM_LIGHT_FREQ,
	/* NAT */
	MSG_RM_FORMAT_TFCARD,
	MSG_RM_GET_CAPACITY,
	MSG_RM_TAKE_PICTURE,
	MSG_RM_GET_FILELIST,
	MSG_RM_DEL_FILE,
	MSG_CDRMAIN_CUR_WINDOW_CHANGED,
	MSG_RM_RECORD_SOUND,
	MSG_AWMD,
	MSG_WATER_MARK,
	MSG_REFRESH,
	MSG_BATTERY_CHANGED,
	MSG_BATTERY_CHARGING,

	MSG_CONNECT2PC,
	MSG_DISCONNECT_FROM_PC,
	MSG_SESSIONCONNECT,
	MSG_SESSIONDISCONNECT,
	MSG_CLOSE_CONNECT2PC_DIALOG,
	MSG_SHOW_CDR_DIALOG,
	MSG_CLOSE_CDR_DIALOG,
	MSG_SHOW_TIP_LABEL,
	MSG_SHOW_TIP_LABEL_FULLSCREEN,
	MSG_CLOSE_TIP_LABEL,
	MSG_FORMAT_TFDIALOG,
	/* set the progress bar time */
	PGBM_SETTIME_RANGE,
	PGBM_SETCURTIME,

	MLM_HILIGHTED_SPACE,	/* 设置MenuList被选中的高亮的item到window边框的距离 */
	MLM_NEW_SELECTED,		/**** 选中了新的item *******/

	/* ************* Status Bar message ******************* */
	STBM_SHOW_HWND,
	STBM_SHOW_BACKBT,
	STBM_SHOW_RECBT,
	STBM_SHOW_PICBT,
	STBM_START_RECORD_TIMER,
	STBM_STOP_RECORD_TIMER,
	STBM_RESUME_RECORD_TIMER,
	STBM_GET_RECORD_TIME,
	STBM_UPDATE_TIME,
	STBM_SETLABEL1_TEXT,
	STBM_CLEAR_LABEL1_TEXT,
	STBM_DIGHT_ZOOM,
	STBM_VIDEO_RESOLUTION,	// wParam is the select index
	STBM_LOOPCOVERAGE,
	STBM_RECORD_SOUND,
	STBM_PHOTO_RESOLUTION,
	STBM_PHOTO_COMPRESSION_QUALITY,
	STBM_PHOTO_TIME_TAKEPHOTOS,
	STBM_PHOTO_AUTOMATIC_TAKEPHOTOS,
	STBM_PHOTO_MOTION_TAKEPHOTOS,
	STBM_MOUNT_TFCARD,
	STBM_UVC,
	STBM_WIFI,
	STBM_GSENSOR,
	STBM_PARK,
	STBM_AWMD,
	STBM_LOCK,
	STBM_COUNT_ONCE,
	STBM_SETLABEL,		// wParam label id, lParam data
	STBM_SETICON,		// wParam icon id, lParam data
	STBM_SET_FILELIST,  // lParam is the str addr
	STBM_SET_FILETOTAL,  // lParam is the str addr
	STBM_FILE_STATUS,
	STBM_VIDEO_DELAYP,
	STBM_VIDEO_SLOWP,
	STBM_PHOTO_TIMEOUT,
	/**************** PlayBack Preview  Message ******************/
	MSG_PLB_COMPLETE,
	MSG_UPDATE_LIST,
	MSG_PREPARE_PLAYBACK,
	MSG_SET_VOLUME,
	MSG_MP_CHANGE_WINDOW,
#ifdef HERO_OLEDUI
	/**************** OLEDUI  Message ******************/
	MSG_INIT_TIMER_RESOURCE,
	MSG_RELEASE_TIMER_RESOURCE,
	MSG_OLED_MOUNT_TFCARD,
	MSG_OLED_MODE_STATUS,
	MSG_OLED_BATTERY_CHANGED,
	MSG_OLED_WIFI_STATUS,
	MSG_OLED_REC_RESOLUTION,
	MSG_OLED_PHOTO_RESOLUTION,
	MSG_OLED_SCREEN_STATUS,
	MSG_OLED_SHUTDOWN,
	MSG_OLED_CONNECT2PC,
	MSG_OLED_DISCONNECT_FROM_PC,
	MSG_OLED_TFCARD_FULL,
#endif
	MSG_OW_CHANGE_FUNC,
	/**************** MainWindow Message *******************/
	/* old_window ---> new_window, wParam is the old window ID */
	MWM_CHANGE_FROM_WINDOW,
	MWM_CHANGE_FROM_WINDOW_EX,
	/* wParam: old window, lParam: new window */
	MWM_CHANGE_WINDOW,
	MSG_WINDOW_CHANGED,
	MSG_SHOW_CDR_WIFIINFO,
    MSG_DRIVING_MODE_SWITCH,
	MSG_WIFI_SWITCH,
	MSG_CLOSE_CDR_WIFI,	
	MSG_OTA_UPDATE,
	MSG_RESET_WIFI_PWD,
	MSG_SET_CURRENT_FILEID,
	MSG_DRAW_ALIGN_LINE,
	MSG_ADAS_SCREEN,
	MSG_GSENSOR_SENSITIVITY,
	MSG_PARK_SENSITIVITY,
	MSG_AUTO_SHUTDOWN,
#ifdef APP_ADAS
	MSG_ADAS_SWITCH,
	MSG_KEEP_ADAS_SCREEN_FLAG,
	MSG_RECOVER_ADAS_SCREEN_FLAG,
#endif
	MSG_CARD_SPEED_DISPLY,
	MSG_CARD_DISPLY_LABLE,
	MSG_FORMAT_TFCARD_FINISH,
	MSG_FORMAT_TFCARD_NOW,
	MSG_STOP_PREVIEW,
	MSG_WIFI_LED_FLASH,
	MSG_WIFI_OPEN_CTRL,
	MSG_RM_VIDEO_DELAYP,
	MSG_RM_VIDEO_SLOWP,
	MSG_TIME_TAKE_PHOTO,
	MSG_RM_FACTORY_RESET,
	MSG_RM_IMAGE_ROTATION,
	MSG_DIGHT_ZOOM,
	MSG_FIRWORD_REWIND,
	MSG_UPDATE_BG,
	MSG_SHUT_DOWN,
	MSG_WIFI_SHUT_DOWN,
	MSG_GET_STATE,
	MSG_SHOW_WIFI_INFO,
	MSG_LAYER_CHANGE,
};


typedef enum {
	LANG_CN = 0,
	LANG_TW = 1,
	LANG_EN = 2,
	LANG_JPN = 3, //日语
	LANG_KR = 4,  //韩语
	LANG_RS = 5,  //俄语
    LANG_DE = 6,  //德语
    LANG_FR = 7,  //法语
    LANG_IT = 8,  //意大利语
    LANG_ES = 9,  //西班牙语
    LANG_PL = 10,  //波兰语
	LANG_ERR
}LANGUAGE;

#endif
